apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-api
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: public
    server: 'https://kubernetes.default.svc'
  source:
    path: public-api/overlays/production/
    repoURL: 'git@github.com:cachac/ops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
